"""quiz_model_etc

Revision ID: 1eb4e02d4b21
Revises: 99c0fd2324e5
Create Date: 2025-10-20 17:50:09.817633

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1eb4e02d4b21'
down_revision = '99c0fd2324e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz',
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quizexercise',
    sa.Column('quiz_id', sa.Uuid(), nullable=False),
    sa.Column('exercise_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.PrimaryKeyConstraint('quiz_id', 'exercise_id')
    )
    op.add_column('exercise', sa.Column('false_answers', sa.JSON))
    
    # Шаг 2: Заполняем существующие записи пустым списком
    op.execute("UPDATE exercise SET false_answers = '[]'::json WHERE false_answers IS NULL")
    
    # Шаг 3: Добавляем ограничение NOT NULL
    op.alter_column('exercise', 'false_answers',
                    existing_type=sa.JSON,
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise', 'false_answers')
    op.drop_table('quizexercise')
    op.drop_table('quiz')
    # ### end Alembic commands ###
