"""fixes_to_db

Revision ID: 2475ba8122ad
Revises: 462bcdf46acc
Create Date: 2025-12-03 13:10:20.676811

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2475ba8122ad'
down_revision = '462bcdf46acc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attachment_module_id'), table_name='attachment')
    op.drop_index(op.f('ix_attachment_type'), table_name='attachment')
    op.drop_constraint(op.f('attachment_module_id_fkey'), 'attachment', type_='foreignkey')
    op.create_foreign_key(None, 'attachment', 'module', ['module_id'], ['id'])
    op.drop_index(op.f('ix_course_author_id'), table_name='course')
    op.drop_index(op.f('ix_course_title'), table_name='course')
    op.drop_constraint(op.f('course_author_id_fkey'), 'course', type_='foreignkey')
    op.create_foreign_key(None, 'course', 'user', ['author_id'], ['id'])
    op.alter_column('module', 'released_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('ix_module_course_id'), table_name='module')
    op.drop_index(op.f('ix_module_order'), table_name='module')
    op.drop_constraint(op.f('module_course_id_fkey'), 'module', type_='foreignkey')
    op.create_foreign_key(None, 'module', 'course', ['course_id'], ['id'])
    op.alter_column('quiz', 'module_id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_index(op.f('fki_M'), table_name='quiz')
    op.drop_index(op.f('idx_active_quiz_per_user'), table_name='quiz', postgresql_where="((status)::text = 'active'::text)")
    op.alter_column('usermoduleprogress', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('usermoduleprogress', 'last_accessed',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('usermoduleprogress', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('ix_usermoduleprogress_module_id'), table_name='usermoduleprogress')
    op.drop_index(op.f('ix_usermoduleprogress_user_id'), table_name='usermoduleprogress')
    op.drop_constraint(op.f('uq_user_module'), 'usermoduleprogress', type_='unique')
    op.drop_constraint(op.f('usermoduleprogress_user_id_fkey'), 'usermoduleprogress', type_='foreignkey')
    op.drop_constraint(op.f('usermoduleprogress_module_id_fkey'), 'usermoduleprogress', type_='foreignkey')
    op.create_foreign_key(None, 'usermoduleprogress', 'module', ['module_id'], ['id'])
    op.create_foreign_key(None, 'usermoduleprogress', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usermoduleprogress', type_='foreignkey')
    op.drop_constraint(None, 'usermoduleprogress', type_='foreignkey')
    op.create_foreign_key(op.f('usermoduleprogress_module_id_fkey'), 'usermoduleprogress', 'module', ['module_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('usermoduleprogress_user_id_fkey'), 'usermoduleprogress', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_user_module'), 'usermoduleprogress', ['user_id', 'module_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_usermoduleprogress_user_id'), 'usermoduleprogress', ['user_id'], unique=False)
    op.create_index(op.f('ix_usermoduleprogress_module_id'), 'usermoduleprogress', ['module_id'], unique=False)
    op.alter_column('usermoduleprogress', 'completed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('usermoduleprogress', 'last_accessed',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('usermoduleprogress', 'started_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.create_index(op.f('idx_active_quiz_per_user'), 'quiz', ['owner_id'], unique=True, postgresql_where="((status)::text = 'active'::text)")
    op.create_index(op.f('fki_M'), 'quiz', ['module_id'], unique=False)
    op.alter_column('quiz', 'module_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'module', type_='foreignkey')
    op.create_foreign_key(op.f('module_course_id_fkey'), 'module', 'course', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_module_order'), 'module', ['order'], unique=False)
    op.create_index(op.f('ix_module_course_id'), 'module', ['course_id'], unique=False)
    op.alter_column('module', 'released_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.create_foreign_key(op.f('course_author_id_fkey'), 'course', 'user', ['author_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_course_title'), 'course', ['title'], unique=False)
    op.create_index(op.f('ix_course_author_id'), 'course', ['author_id'], unique=False)
    op.drop_constraint(None, 'attachment', type_='foreignkey')
    op.create_foreign_key(op.f('attachment_module_id_fkey'), 'attachment', 'module', ['module_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_attachment_type'), 'attachment', ['type'], unique=False)
    op.create_index(op.f('ix_attachment_module_id'), 'attachment', ['module_id'], unique=False)
    # ### end Alembic commands ###
