"""folded everything into 1 migration

Revision ID: 462bcdf46acc
Revises: 
Create Date: 2025-11-27 15:18:42.495310

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '462bcdf46acc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise',
    sa.Column('source_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('illustration', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('solution', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)

    op.create_table('item',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(["module_id"], ["module.id"], ondelete="CASCADE"),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quizexercise',
    sa.Column('quiz_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exercise_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('quiz_id', 'exercise_id')
    )
    op.create_index(
    'idx_active_quiz_per_user',
    'quiz',
    ['owner_id'],
    unique=True,
    postgresql_where=sa.sql.text("status = 'active'")
    )
    op.create_table('course',
        sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('author_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('module_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('attendant_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(['author_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_author_id'), 'course', ['author_id'])
    op.create_index(op.f('ix_course_title'), 'course', ['title'])
    op.create_table('module',
        sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('order', sa.Integer(), nullable=False),
        sa.Column('is_draft', sa.Boolean(), nullable=False),
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('course_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('attachment_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('quiz_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_module_course_id'), 'module', ['course_id'])
    op.create_index(op.f('ix_module_order'), 'module', ['order'])

    op.create_table('attachment',
        sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('order', sa.Integer(), nullable=False),
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('module_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(['module_id'], ['module.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachment_module_id'), 'attachment', ['module_id'])
    op.create_index(op.f('ix_attachment_type'), 'attachment', ['type'])

    op.create_table('usermoduleprogress',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('module_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('last_accessed', sa.DateTime(timezone=True), nullable=False),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('is_completed', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['module_id'], ['module.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'module_id', name='uq_user_module')  # One progress per user+module
    )
    op.create_index(op.f('ix_usermoduleprogress_user_id'), 'usermoduleprogress', ['user_id'])
    op.create_index(op.f('ix_usermoduleprogress_module_id'), 'usermoduleprogress', ['module_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop tables in reverse order of creation
    op.drop_table('item')
    op.drop_table('usermoduleprogress')
    op.drop_table('quizexercise')
    op.drop_table('quiz')
    op.drop_table('attachment')
    op.drop_table('module')
    op.drop_table('course')
    op.drop_table('exercise')
    op.drop_table('user')

    # Drop indexes manually since some were created with conditions or not tracked
    op.drop_index('idx_active_quiz_per_user', table_name='quiz', type_='unique')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_course_author_id'), table_name='course')
    op.drop_index(op.f('ix_course_title'), table_name='course')
    op.drop_index(op.f('ix_module_course_id'), table_name='module')
    op.drop_index(op.f('ix_module_order'), table_name='module')
    op.drop_index(op.f('ix_attachment_module_id'), table_name='attachment')
    op.drop_index(op.f('ix_attachment_type'), table_name='attachment')
    op.drop_index(op.f('ix_quiz_owner_id'), table_name='quiz')
    op.drop_index(op.f('ix_quiz_status'), table_name='quiz')
    op.drop_index(op.f('ix_quizexercise_exercise_id'), table_name='quizexercise')
    op.drop_index(op.f('ix_usermoduleprogress_user_id'), table_name='usermoduleprogress')
    op.drop_index(op.f('ix_usermoduleprogress_module_id'), table_name='usermoduleprogress')
    op.drop_index(op.f('ix_item_owner_id'), table_name='item')