"""course_module_link_not_needed

Revision ID: 484f0a3c81aa
Revises: eb7f41c148f9
Create Date: 2025-12-11 00:01:08.552426

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '484f0a3c81aa'
down_revision = 'eb7f41c148f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coursemodules')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coursemodules',
    sa.Column('course_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('module_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('coursemodules_course_id_fkey')),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], name=op.f('coursemodules_module_id_fkey')),
    sa.PrimaryKeyConstraint('course_id', 'module_id', name=op.f('coursemodules_pkey'))
    )
    # ### end Alembic commands ###
