"""add_cascade_to_quizexercises

Revision ID: 4b8bf1887615
Revises: 8268785014a1
Create Date: 2025-10-23 23:18:18.252134

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4b8bf1887615'
down_revision = '8268785014a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('quizexercise_quiz_id_fkey'), 'quizexercise', type_='foreignkey')
    op.drop_constraint(op.f('quizexercise_exercise_id_fkey'), 'quizexercise', type_='foreignkey')
    op.create_foreign_key(None, 'quizexercise', 'quiz', ['quiz_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'quizexercise', 'exercise', ['exercise_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quizexercise', type_='foreignkey')
    op.drop_constraint(None, 'quizexercise', type_='foreignkey')
    op.create_foreign_key(op.f('quizexercise_exercise_id_fkey'), 'quizexercise', 'exercise', ['exercise_id'], ['id'])
    op.create_foreign_key(op.f('quizexercise_quiz_id_fkey'), 'quizexercise', 'quiz', ['quiz_id'], ['id'])
    # ### end Alembic commands ###
