"""add_exercise_tag_exercisetag_tables

Revision ID: 59b5bde62418
Revises: f4eca31c86f8
Create Date: 2025-10-17 14:52:58.941926

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '59b5bde62418'
down_revision = 'f4eca31c86f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'exercise',
        sa.Column('source_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('solution', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('formula', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('illustration', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_table('tag',
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(
        op.f('ix_tag_name'),
        'tag',
        ['name'],
        unique=True)
    op.create_table(
        'exercisetag',
        sa.Column('exercise_id', sa.Uuid(), nullable=False),
        sa.Column('tag_id', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
        sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
        sa.PrimaryKeyConstraint('exercise_id', 'tag_id')
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercisetag')
    op.drop_index(op.f('ix_tag_name'), table_name='tag')
    op.drop_table('tag')
    op.drop_table('exercise')
    # ### end Alembic commands ###
