"""quiz_model_update_and_uuid7

Revision ID: 5d80898f4621
Revises: 4b8bf1887615
Create Date: 2025-10-30 16:58:55.900904

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5d80898f4621'
down_revision = '4b8bf1887615'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercisetag')
    op.drop_index(op.f('ix_tag_name'), table_name='tag')
    op.drop_table('tag')
    op.add_column('exercise', sa.Column('answers', sa.JSON(), nullable=True))
    op.add_column('exercise', sa.Column('tags', sa.JSON(), nullable=True))
    op.alter_column('exercise', 'illustration',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='illustration::json')
    op.drop_column('exercise', 'false_answers')
    op.drop_column('exercise', 'formula')
    op.add_column('quiz', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('quizexercise', sa.Column('position', sa.Integer(), nullable=False))
    op.add_column('quizexercise', sa.Column('is_solved', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizexercise', 'is_solved')
    op.drop_column('quizexercise', 'position')
    op.drop_column('quiz', 'title')
    op.add_column('exercise', sa.Column('formula', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('exercise', sa.Column('false_answers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.alter_column('exercise', 'illustration',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('exercise', 'tags')
    op.drop_column('exercise', 'answers')
    op.create_table('tag',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='tag_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_tag_name'), 'tag', ['name'], unique=True)
    op.create_table('exercisetag',
    sa.Column('exercise_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], name=op.f('exercisetag_exercise_id_fkey')),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('exercisetag_tag_id_fkey')),
    sa.PrimaryKeyConstraint('exercise_id', 'tag_id', name=op.f('exercisetag_pkey'))
    )
    # ### end Alembic commands ###
