"""add_exercises_public_table

Revision ID: 6a441627909e
Revises: 59b5bde62418
Create Date: 2025-10-17 15:58:15.587020

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6a441627909e'
down_revision = '59b5bde62418'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
