"""module_attachment_link

Revision ID: 84308f9eb50a
Revises: 9c399eb90535
Create Date: 2025-12-08 23:03:15.505615

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '84308f9eb50a'
down_revision = '9c399eb90535'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moduleattachments',
    sa.Column('module_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attachment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachment.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], ),
    sa.PrimaryKeyConstraint('module_id', 'attachment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moduleattachments')
    # ### end Alembic commands ###
