"""fix_links

Revision ID: 88227d39466f
Revises: e3a64f8302c1
Create Date: 2025-12-03 14:37:41.751181

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '88227d39466f'
down_revision = 'e3a64f8302c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coursemodules',
    sa.Column('course_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('module_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], ),
    sa.PrimaryKeyConstraint('course_id', 'module_id')
    )
    op.drop_table('coursemodulelink')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coursemodulelink',
    sa.Column('course_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('module_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('coursemodulelink_course_id_fkey')),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], name=op.f('coursemodulelink_module_id_fkey')),
    sa.PrimaryKeyConstraint('course_id', 'module_id', name=op.f('coursemodulelink_pkey'))
    )
    op.drop_table('coursemodules')
    # ### end Alembic commands ###
