"""fixing_ai_slop

Revision ID: 9319fecc5f23
Revises: 84308f9eb50a
Create Date: 2025-12-08 23:24:22.659961

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9319fecc5f23'
down_revision = '84308f9eb50a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moduleattachments')
    op.add_column('attachment', sa.Column('module_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_foreign_key(None, 'attachment', 'module', ['module_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attachment', type_='foreignkey')
    op.drop_column('attachment', 'module_id')
    op.create_table('moduleattachments',
    sa.Column('module_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('attachment_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachment.id'], name=op.f('moduleattachments_attachment_id_fkey')),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], name=op.f('moduleattachments_module_id_fkey')),
    sa.PrimaryKeyConstraint('module_id', 'attachment_id', name=op.f('moduleattachments_pkey'))
    )
    # ### end Alembic commands ###
