"""more_tags_and_exercises_tables

Revision ID: 99c0fd2324e5
Revises: 6a441627909e
Create Date: 2025-10-17 21:09:38.419943

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '99c0fd2324e5'
down_revision = '6a441627909e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
