"""removed_excessive_id_links

Revision ID: 9c399eb90535
Revises: bf2ba228526e
Create Date: 2025-12-08 22:56:52.689623

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9c399eb90535'
down_revision = 'bf2ba228526e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('attachment_module_id_fkey'), 'attachment', type_='foreignkey')
    op.drop_column('attachment', 'module_id')
    op.drop_column('course', 'attendant_ids')
    op.drop_column('course', 'module_ids')
    op.drop_constraint(op.f('module_course_id_fkey'), 'module', type_='foreignkey')
    op.drop_column('module', 'quiz_ids')
    op.drop_column('module', 'course_id')
    op.drop_column('module', 'attachment_ids')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module', sa.Column('attachment_ids', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('module', sa.Column('course_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('module', sa.Column('quiz_ids', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('module_course_id_fkey'), 'module', 'course', ['course_id'], ['id'])
    op.add_column('course', sa.Column('module_ids', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('course', sa.Column('attendant_ids', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('attachment', sa.Column('module_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('attachment_module_id_fkey'), 'attachment', 'module', ['module_id'], ['id'])
    # ### end Alembic commands ###
