"""changing_quiz_status

Revision ID: ad31197481d1
Revises: 5a1c526d0c22
Create Date: 2025-11-06 15:56:00.138583

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ad31197481d1'
down_revision = '5a1c526d0c22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz', sa.Column('status', sa.String(), nullable=False))
    op.drop_column('quiz', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('quiz', 'status')
    # ### end Alembic commands ###
