"""changing_quiz_status

Revision ID: b761b73e6061
Revises: ad31197481d1
Create Date: 2025-11-06 16:48:06.431115

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b761b73e6061'
down_revision = 'ad31197481d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizexercise', sa.Column('is_correct', sa.Boolean(), nullable=True))
    op.drop_column('quizexercise', 'is_solved')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizexercise', sa.Column('is_solved', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('quizexercise', 'is_correct')
    # ### end Alembic commands ###
