"""modules_not_required_for_attachments

Revision ID: bf2ba228526e
Revises: 88227d39466f
Create Date: 2025-12-08 22:33:25.356008

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'bf2ba228526e'
down_revision = '88227d39466f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attachment', 'module_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attachment', 'module_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
