"""fixing_ai_slop

Revision ID: c507aafd63c9
Revises: 9319fecc5f23
Create Date: 2025-12-08 23:32:30.962233

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c507aafd63c9'
down_revision = '9319fecc5f23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attachment', 'module_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attachment', 'module_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
