"""added weights to exercises

Revision ID: e9f03d495ebe
Revises: a1a8ec6a0369
Create Date: 2026-01-07 07:53:59.783480

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e9f03d495ebe'
down_revision = 'a1a8ec6a0369'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('weight', sa.Integer(), nullable=False))
    op.add_column('quiz', sa.Column('total_weight', sa.Integer(), nullable=False))
    op.alter_column('quiz', 'final_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index(op.f('idx_active_quiz_per_user'), table_name='quiz', postgresql_where="((status)::text = 'active'::text)")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_active_quiz_per_user'), 'quiz', ['owner_id'], unique=True, postgresql_where="((status)::text = 'active'::text)")
    op.alter_column('quiz', 'final_score',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_column('quiz', 'total_weight')
    op.drop_column('exercise', 'weight')
    # ### end Alembic commands ###
