"""enforcing_unique_positions

Revision ID: eb7f41c148f9
Revises: ec00116abfdf
Create Date: 2025-12-10 02:04:20.717864

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'eb7f41c148f9'
down_revision = 'ec00116abfdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_attachment_order_per_module', 'attachment', ['module_id', 'order'])
    op.add_column('module', sa.Column('course_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_unique_constraint('unique_module_order_per_course', 'module', ['course_id', 'order'])
    op.create_foreign_key(None, 'module', 'course', ['course_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'module', type_='foreignkey')
    op.drop_constraint('unique_module_order_per_course', 'module', type_='unique')
    op.drop_column('module', 'course_id')
    op.drop_constraint('unique_attachment_order_per_module', 'attachment', type_='unique')
    # ### end Alembic commands ###
