"""added_author_to_modules

Revision ID: ec00116abfdf
Revises: c507aafd63c9
Create Date: 2025-12-09 22:23:54.382643

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ec00116abfdf'
down_revision = 'c507aafd63c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module', sa.Column('author_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_foreign_key(None, 'module', 'user', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'module', type_='foreignkey')
    op.drop_column('module', 'author_id')
    # ### end Alembic commands ###
