"""added tokens to courses

Revision ID: f2f31fd679ac
Revises: e9f03d495ebe
Create Date: 2026-01-08 07:24:01.267916

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f2f31fd679ac'
down_revision = 'e9f03d495ebe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('course', sa.Column('token_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'token_expires_at')
    op.drop_column('course', 'token')
    # ### end Alembic commands ###
